apiVersion: apps/v1
kind: Deployment
metadata:
  name:
spec:
  replicas: 3
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name:
          image:
          ports:
            - containerPort:
          env:
            - name: PORT
              value: "8080"
          livenessProbe:
            periodSeconds: 5
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8080" ]
          readinessProbe:
            periodSeconds: 5
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8080" ]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi