apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol:
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}